### ISSUE TITLE
运行 demo 程序遇到了一点小问题

### ISSUE THREAD

**Issue by huangyong-git** [oldmanpushcart/excavator#1]
您好！

这款框架我非常喜欢，迫不及待想去学习。运行了您提供的 demo 程序，但出现如下异常：

```
2014-11-08 10:23:46 [com.netflix.curator.framework.recipes.cache.PathChildrenCache]-[ERROR] 
java.lang.IllegalStateException
    at com.google.common.base.Preconditions.checkState(Preconditions.java:133)
    at com.netflix.curator.framework.imps.CuratorFrameworkImpl.getChildren(CuratorFrameworkImpl.java:294)
    at com.netflix.curator.framework.recipes.cache.PathChildrenCache.refresh(PathChildrenCache.java:361)
    at com.netflix.curator.framework.recipes.cache.PathChildrenCache.access$300(PathChildrenCache.java:64)
    at com.netflix.curator.framework.recipes.cache.PathChildrenCache$4.process(PathChildrenCache.java:352)
    at com.netflix.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:38)
    at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:521)
    at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:497)
```

第一次运行失败，第二次运行就成功了，第三次运行又失败了，就像这样反复成功与失败交替，不知具体是什么原因造成，还请您赐教，谢谢！

备注：我使用的是 ZooKeeper 3.4.6，单机模式，运行在 Windows 7 环境下。

**Comment by oldmanpushcart** [comment]
我不记得有提供demo了，能否给我看下你得到的demo？

**Comment by huangyong-git** [comment]
我在 `快速开始` 文档中看到的，地址如下：

http://dl.iteye.com/topics/download/b6c3563c-2bf0-3b9c-9dc2-65d53e17fffa

**Comment by oldmanpushcart** [comment]
我可能要更新下我的demo了，给我1个小时

**Comment by huangyong-git** [comment]
太感谢了！最好能创建一个 github 项目那就更好了 :)

**Comment by oldmanpushcart** [comment]
已经创建了一个项目 [excavator-demo](https://github.com/oldmanpushcart/excavator-demo)

**Comment by huangyong-git** [comment]
我已 clone 这个最新的 demo 项目，但仍然会出现如下报错信息：

```
hello vlinux!
19:52:24,160 [main-EventThread] ERROR PathChildrenCache@handleException:
java.lang.IllegalStateException
    at com.google.common.base.Preconditions.checkState(Preconditions.java:133)
    at com.netflix.curator.framework.imps.CuratorFrameworkImpl.getChildren(CuratorFrameworkImpl.java:294)
    at com.netflix.curator.framework.recipes.cache.PathChildrenCache.refresh(PathChildrenCache.java:361)
    at com.netflix.curator.framework.recipes.cache.PathChildrenCache.access$300(PathChildrenCache.java:64)
    at com.netflix.curator.framework.recipes.cache.PathChildrenCache$4.process(PathChildrenCache.java:352)
    at com.netflix.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:38)
    at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:521)
    at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:497)
```

请问 ZooKeeper 还需要哪些配置吗？

**Comment by oldmanpushcart** [comment]
已经能输出了正确的信息

```
hello vlinux!
```

不过你这个问题还的确是奇怪，ZooKeeper使用默认的zoo.cfg即可，劳烦将Log4j的DEBUG打开，我想看看更多的信息

**Comment by huangyong-git** [comment]
zoo.cfg 使用的默认配置，将 log4j 设置为 debug 级别后，产生了如下日志：

```
21:44:23,891 [main] INFO  AbstractApplicationContext@prepareRefresh:Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@3d74098f: display name [org.springframework.context.support.ClassPathXmlApplicationContext@3d74098f]; startup date [Sat Nov 08 21:44:23 CST 2014]; root of context hierarchy
21:44:24,010 [main] INFO  XmlBeanDefinitionReader@loadBeanDefinitions:Loading XML bean definitions from class path resource [applicationContext.xml]
21:44:24,016 [main] DEBUG DefaultDocumentLoader@loadDocument:Using JAXP provider [com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl]
21:44:24,056 [main] DEBUG BeansDtdResolver@resolveEntity:Found beans DTD [http://www.springframework.org/dtd/spring-beans.dtd] in classpath: spring-beans.dtd
21:44:24,087 [main] DEBUG DefaultBeanDefinitionDocumentReader@registerBeanDefinitions:Loading bean definitions
21:44:24,120 [main] DEBUG BeanDefinitionParserDelegate@parseBeanDefinitionElement:Neither XML 'id' nor 'name' specified - using generated bean name [com.googlecode.excavator.demo.service.impl.HelloServiceImpl#2528ed7]
21:44:24,123 [main] DEBUG BeanDefinitionParserDelegate@parseBeanDefinitionElement:Neither XML 'id' nor 'name' specified - using generated bean name [com.googlecode.excavator.spring.ExcavatorProviderSpringFactoryBean#0]
21:44:24,128 [main] DEBUG AbstractBeanDefinitionReader@loadBeanDefinitions:Loaded 2 bean definitions from location pattern [applicationContext.xml]
21:44:24,129 [main] INFO  AbstractApplicationContext@obtainFreshBeanFactory:Bean factory for application context [org.springframework.context.support.ClassPathXmlApplicationContext@3d74098f]: org.springframework.beans.factory.support.DefaultListableBeanFactory@29a9fe14
21:44:24,130 [main] DEBUG AbstractApplicationContext@obtainFreshBeanFactory:2 beans defined in org.springframework.context.support.ClassPathXmlApplicationContext@3d74098f: display name [org.springframework.context.support.ClassPathXmlApplicationContext@3d74098f]; startup date [Sat Nov 08 21:44:23 CST 2014]; root of context hierarchy
21:44:24,146 [main] DEBUG AbstractApplicationContext@initMessageSource:Unable to locate MessageSource with name 'messageSource': using default [org.springframework.context.support.DelegatingMessageSource@3e963f38]
21:44:24,150 [main] DEBUG AbstractApplicationContext@initApplicationEventMulticaster:Unable to locate ApplicationEventMulticaster with name 'applicationEventMulticaster': using default [org.springframework.context.event.SimpleApplicationEventMulticaster@67aaecbe]
21:44:24,152 [main] INFO  DefaultListableBeanFactory@preInstantiateSingletons:Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@29a9fe14: defining beans [com.googlecode.excavator.spring.ExcavatorProviderSpringFactoryBean#0,helloService]; root of factory hierarchy
21:44:24,154 [main] DEBUG DefaultSingletonBeanRegistry@getSingleton:Creating shared instance of singleton bean 'com.googlecode.excavator.spring.ExcavatorProviderSpringFactoryBean#0'
21:44:24,156 [main] DEBUG AbstractAutowireCapableBeanFactory$1@run:Creating instance of bean 'com.googlecode.excavator.spring.ExcavatorProviderSpringFactoryBean#0'
21:44:24,183 [main] DEBUG AbstractAutowireCapableBeanFactory@doCreateBean:Eagerly caching bean 'com.googlecode.excavator.spring.ExcavatorProviderSpringFactoryBean#0' to allow for resolving potential circular references
21:44:24,201 [main] DEBUG AbstractAutowireCapableBeanFactory$1@run:Creating instance of bean 'com.googlecode.excavator.demo.service.impl.HelloServiceImpl#2528ed7'
21:44:24,202 [main] DEBUG AbstractAutowireCapableBeanFactory$1@run:Finished creating instance of bean 'com.googlecode.excavator.demo.service.impl.HelloServiceImpl#2528ed7'
21:44:24,218 [main] DEBUG AbstractAutowireCapableBeanFactory@invokeInitMethods:Invoking afterPropertiesSet() on bean with name 'com.googlecode.excavator.spring.ExcavatorProviderSpringFactoryBean#0'
21:44:24,254 [main] INFO  PropertyConfiger@preloadMonitorEnable:excavator.monitor.enable=true
21:44:24,260 [main] INFO  PropertyConfiger@preloadAppName:excavator.appname=excavator_demo
21:44:24,260 [main] INFO  PropertyConfiger@preloadTokenEnable:excavator.token=false
21:44:24,262 [main] INFO  PropertyConfiger@preloadProfilerLimit:excavator.profiler.limit=1
21:44:24,262 [main] INFO  PropertyConfiger@preloadProfilerEnable:excavator.profiler.enable=true
21:44:24,262 [main] INFO  PropertyConfiger@preloadSerializer:excavator.serializer.name=hessian
21:44:24,505 [main] INFO  PropertyConfiger@preloadAddress:address=/192.168.65.1:3659
21:44:24,552 [main] INFO  WorkerSupport@init:worker init thread_pool size:250
21:44:24,666 [main] INFO  ServerSupport@init:server was started at /192.168.65.1:3659
21:44:24,700 [main] INFO  CuratorFrameworkImpl@start:Starting
21:44:24,700 [main] DEBUG CuratorZookeeperClient@start:Starting
21:44:24,700 [main] DEBUG ConnectionState@start:Starting
21:44:24,724 [main] INFO  Environment@logEnv:Client environment:zookeeper.version=3.4.3-1240972, built on 02/06/2012 10:48 GMT
21:44:24,724 [main] INFO  Environment@logEnv:Client environment:host.name=LSH07YONGHUANG.ycmsh.com
21:44:24,725 [main] INFO  Environment@logEnv:Client environment:java.version=1.7.0_65
21:44:24,725 [main] INFO  Environment@logEnv:Client environment:java.vendor=Oracle Corporation
21:44:24,726 [main] INFO  Environment@logEnv:Client environment:java.home=C:\Program Files\Java\jdk1.7.0_65\jre
21:44:24,726 [main] INFO  Environment@logEnv:Client environment:java.class.path=C:\Program Files\Java\jdk1.7.0_65\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\jce.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\jfxrt.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\resources.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\rt.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.7.0_65\jre\lib\ext\zipfs.jar;D:\project\excavator-demo\target\classes;C:\Users\yong.huang\.m2\repository\com\googlecode\excavator\excavator\1.1.5-SNAPSHOT\excavator-1.1.5-20140902.094415-9.jar;C:\Users\yong.huang\.m2\repository\org\apache\zookeeper\zookeeper\3.4.3\zookeeper-3.4.3.jar;C:\Users\yong.huang\.m2\repository\org\slf4j\slf4j-log4j12\1.6.1\slf4j-log4j12-1.6.1.jar;C:\Users\yong.huang\.m2\repository\log4j\log4j\1.2.15\log4j-1.2.15.jar;C:\Users\yong.huang\.m2\repository\javax\mail\mail\1.4\mail-1.4.jar;C:\Users\yong.huang\.m2\repository\javax\activation\activation\1.1\activation-1.1.jar;C:\Users\yong.huang\.m2\repository\jline\jline\0.9.94\jline-0.9.94.jar;C:\Users\yong.huang\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;C:\Users\yong.huang\.m2\repository\com\netflix\curator\curator-recipes\1.1.3\curator-recipes-1.1.3.jar;C:\Users\yong.huang\.m2\repository\com\netflix\curator\curator-framework\1.1.3\curator-framework-1.1.3.jar;C:\Users\yong.huang\.m2\repository\com\netflix\curator\curator-client\1.1.3\curator-client-1.1.3.jar;C:\Users\yong.huang\.m2\repository\com\caucho\hessian\4.0.7\hessian-4.0.7.jar;C:\Users\yong.huang\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;C:\Users\yong.huang\.m2\repository\io\netty\netty\3.5.2.Final\netty-3.5.2.Final.jar;C:\Users\yong.huang\.m2\repository\org\slf4j\slf4j-api\1.6.6\slf4j-api-1.6.6.jar;C:\Users\yong.huang\.m2\repository\com\google\guava\guava\13.0-rc1\guava-13.0-rc1.jar;C:\Users\yong.huang\.m2\repository\org\springframework\spring\2.5.6\spring-2.5.6.jar;C:\Users\yong.huang\.m2\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.0\lib\idea_rt.jar
21:44:24,735 [main] INFO  Environment@logEnv:Client environment:java.library.path=C:\Program Files\Java\jdk1.7.0_65\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Lenovo\Fingerprint Manager Pro\;C:\Program Files\Java\jdk1.7.0_65\bin;D:\tool\maven\bin;C:\Program Files\TortoiseSVN\bin;D:\tool\mysql\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\GNU\GnuPG\pub;.
21:44:24,736 [main] INFO  Environment@logEnv:Client environment:java.io.tmpdir=C:\Users\YONG~1.HUA\AppData\Local\Temp\
21:44:24,736 [main] INFO  Environment@logEnv:Client environment:java.compiler=<NA>
21:44:24,737 [main] INFO  Environment@logEnv:Client environment:os.name=Windows 7
21:44:24,737 [main] INFO  Environment@logEnv:Client environment:os.arch=amd64
21:44:24,737 [main] INFO  Environment@logEnv:Client environment:os.version=6.1
21:44:24,739 [main] INFO  Environment@logEnv:Client environment:user.name=Yong.Huang
21:44:24,739 [main] INFO  Environment@logEnv:Client environment:user.home=C:\Users\yong.huang
21:44:24,739 [main] INFO  Environment@logEnv:Client environment:user.dir=D:\project\excavator-demo
21:44:24,741 [main] INFO  ZooKeeper@<init>:Initiating client connection, connectString=127.0.0.1:2181 sessionTimeout=60000 watcher=com.netflix.curator.ConnectionState@17088d81
21:44:24,745 [main] DEBUG ClientCnxn@<clinit>:zookeeper.disableAutoWatchReset is false
21:44:24,780 [main-SendThread()] INFO  ClientCnxn$SendThread@startConnect:Opening socket connection to server /127.0.0.1:2181
21:44:24,786 [main-SendThread(server:2181)] INFO  ZooKeeperSaslClient@<init>:Client will not SASL-authenticate because the default JAAS configuration section 'Client' could not be found. If you are not using SASL, you may ignore this. On the other hand, if you expected SASL to work, please fix your JAAS configuration.
21:44:24,795 [main-SendThread(server:2181)] INFO  ClientCnxn$SendThread@primeConnection:Socket connection established to server/127.0.0.1:2181, initiating session
21:44:24,800 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@primeConnection:Session establishment request sent on server/127.0.0.1:2181
21:44:24,916 [main-SendThread(server:2181)] INFO  ClientCnxn$SendThread@onConnected:Session establishment complete on server server/127.0.0.1:2181, sessionid = 0x1498fa5e8e80000, negotiated timeout = 40000
21:44:24,932 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@readResponse:Reading reply sessionid:0x1498fa5e8e80000, packet:: clientPath:null serverPath:null finished:false header:: 1,3  replyHeader:: 1,107,0  request:: '/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7,F  response:: s{74,74,1415447516528,1415447516528,0,12,0,0,0,0,102} 
21:44:24,944 [main] DEBUG AbstractAutowireCapableBeanFactory$1@run:Finished creating instance of bean 'com.googlecode.excavator.spring.ExcavatorProviderSpringFactoryBean#0'
21:44:24,945 [main] DEBUG DefaultSingletonBeanRegistry@getSingleton:Creating shared instance of singleton bean 'helloService'
21:44:24,946 [main] DEBUG AbstractAutowireCapableBeanFactory$1@run:Creating instance of bean 'helloService'
21:44:24,946 [main] DEBUG AbstractAutowireCapableBeanFactory@doCreateBean:Eagerly caching bean 'helloService' to allow for resolving potential circular references
21:44:24,952 [main] DEBUG AbstractAutowireCapableBeanFactory@invokeInitMethods:Invoking afterPropertiesSet() on bean with name 'helloService'
21:44:24,970 [main] INFO  CuratorFrameworkImpl@start:Starting
21:44:24,970 [main] DEBUG CuratorZookeeperClient@start:Starting
21:44:24,971 [main] DEBUG ConnectionState@start:Starting
21:44:24,971 [main] INFO  ZooKeeper@<init>:Initiating client connection, connectString=127.0.0.1:2181 sessionTimeout=60000 watcher=com.netflix.curator.ConnectionState@216030f9
21:44:24,998 [main-SendThread()] INFO  ClientCnxn$SendThread@startConnect:Opening socket connection to server /127.0.0.1:2181
21:44:25,006 [main-SendThread(server:2181)] INFO  ZooKeeperSaslClient@<init>:Client will not SASL-authenticate because the default JAAS configuration section 'Client' could not be found. If you are not using SASL, you may ignore this. On the other hand, if you expected SASL to work, please fix your JAAS configuration.
21:44:25,011 [main-SendThread(server:2181)] INFO  ClientCnxn$SendThread@primeConnection:Socket connection established to server/127.0.0.1:2181, initiating session
21:44:25,011 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@primeConnection:Session establishment request sent on server/127.0.0.1:2181
21:44:25,020 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@readResponse:Reading reply sessionid:0x1498fa5e8e80000, packet:: clientPath:/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7/192.168.65.1:3659:excavator_demo serverPath:/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7/192.168.65.1:3659:excavator_demo finished:false header:: 2,1  replyHeader:: 2,108,0  request:: '/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7/192.168.65.1:3659:excavator_demo,,v{s{31,s{'world,'anyone}}},1  response:: '/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7/192.168.65.1:3659:excavator_demo 
21:44:25,056 [main-EventThread] INFO  ServiceRegisterSupport$2@processResult:register service:group=DEFAULT;version=1.0.0-test;sign=dd9beea4b272b1b02b60e12c1ba8c7f7;timeout=60000 successed.
21:44:25,407 [main-SendThread(server:2181)] INFO  ClientCnxn$SendThread@onConnected:Session establishment complete on server server/127.0.0.1:2181, sessionid = 0x1498fa5e8e80001, negotiated timeout = 40000
21:44:25,409 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@readResponse:Reading reply sessionid:0x1498fa5e8e80001, packet:: clientPath:null serverPath:null finished:false header:: 1,3  replyHeader:: 1,109,0  request:: '/excavator,F  response:: s{70,70,1415447516404,1415447516404,0,1,0,0,0,1,71} 
21:44:25,411 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@readResponse:Reading reply sessionid:0x1498fa5e8e80001, packet:: clientPath:null serverPath:null finished:false header:: 2,3  replyHeader:: 2,109,0  request:: '/excavator/nondurable,F  response:: s{71,71,1415447516429,1415447516429,0,1,0,0,0,1,72} 
21:44:25,412 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@readResponse:Reading reply sessionid:0x1498fa5e8e80001, packet:: clientPath:null serverPath:null finished:false header:: 3,3  replyHeader:: 3,109,0  request:: '/excavator/nondurable/DEFAULT,F  response:: s{72,72,1415447516446,1415447516446,0,1,0,0,0,1,73} 
21:44:25,413 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@readResponse:Reading reply sessionid:0x1498fa5e8e80001, packet:: clientPath:null serverPath:null finished:false header:: 4,3  replyHeader:: 4,109,0  request:: '/excavator/nondurable/DEFAULT/1.0.0-test,F  response:: s{73,73,1415447516491,1415447516491,0,1,0,0,0,1,74} 
21:44:25,415 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@readResponse:Reading reply sessionid:0x1498fa5e8e80001, packet:: clientPath:null serverPath:null finished:false header:: 5,3  replyHeader:: 5,109,0  request:: '/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7,F  response:: s{74,74,1415447516528,1415447516528,0,13,0,0,0,1,108} 
21:44:25,419 [main] DEBUG AbstractAutowireCapableBeanFactory$1@run:Finished creating instance of bean 'helloService'
21:44:25,419 [main] DEBUG AbstractBeanFactory@doGetBean:Returning cached instance of singleton bean 'helloService'
21:44:25,443 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@readResponse:Reading reply sessionid:0x1498fa5e8e80001, packet:: clientPath:/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7 serverPath:/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7 finished:false header:: 6,12  replyHeader:: 6,109,0  request:: '/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7,T  response:: v{'192.168.65.1:3659:excavator_demo},s{74,74,1415447516528,1415447516528,0,13,0,0,0,1,108} 
21:44:25,451 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@readResponse:Reading reply sessionid:0x1498fa5e8e80001, packet:: clientPath:/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7/192.168.65.1:3659:excavator_demo serverPath:/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7/192.168.65.1:3659:excavator_demo finished:false header:: 7,3  replyHeader:: 7,109,0  request:: '/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7/192.168.65.1:3659:excavator_demo,F  response:: s{108,108,1415454264948,1415454264948,0,0,0,92763210077700096,0,0,108} 
21:44:25,548 [New I/O  worker #1] INFO  ServerSupport$2@channelConnected:client:/192.168.65.1:64721 was connected.
21:44:25,597 [PathChildrenCache-0] INFO  ChannelRingSupport@createChannel:connect to /192.168.65.1:3659 successed.
21:44:25,600 [PathChildrenCache-0] INFO  ServiceDiscoverySupport$1@childEvent:receive service changed[create]. evnet=PathChildrenCacheEvent{type=CHILD_ADDED, data=ChildData{path='/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7/192.168.65.1:3659:excavator_demo', stat=108,108,1415454264948,1415454264948,0,0,0,92763210077700096,0,0,108
, data=null}}
hello vlinux!
21:44:25,728 [Thread-3] INFO  Monitors@flushMonitorLog:CONSUMER DEFAULT 1.0.0-test  dd9beea4b272b1b02b60e12c1ba8c7f7    excavator_demo  excavator_demo  2   42  
21:44:25,728 [Thread-3] INFO  Monitors@flushMonitorLog:PROVIDER DEFAULT 1.0.0-test  dd9beea4b272b1b02b60e12c1ba8c7f7    excavator_demo  excavator_demo  2   0   
21:44:25,730 [New I/O  worker #1] INFO  ServerSupport$2@channelDisconnected:client:/192.168.65.1:64721 was disconnected.
21:44:25,737 [Thread-1] INFO  ServerSupport@destroy:server was shutdown.
21:44:25,737 [Thread-1] DEBUG CuratorFrameworkImpl@close:Closing
21:44:25,738 [Thread-1] DEBUG CuratorZookeeperClient@close:Closing
21:44:25,739 [Thread-1] DEBUG ConnectionState@close:Closing
21:44:25,739 [Thread-1] DEBUG ZooKeeper@close:Closing session: 0x1498fa5e8e80000
21:44:25,739 [Thread-1] DEBUG ClientCnxn@close:Closing client for session: 0x1498fa5e8e80000
21:44:25,779 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@readResponse:Got notification sessionid:0x1498fa5e8e80001
21:44:25,780 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@readResponse:Reading reply sessionid:0x1498fa5e8e80000, packet:: clientPath:null serverPath:null finished:false header:: 3,-11  replyHeader:: 3,110,0  request:: null response:: null
21:44:25,780 [Thread-2] DEBUG CuratorFrameworkImpl@close:Closing
21:44:25,780 [Thread-2] DEBUG CuratorZookeeperClient@close:Closing
21:44:25,781 [Thread-2] DEBUG ConnectionState@close:Closing
21:44:25,781 [Thread-2] DEBUG ZooKeeper@close:Closing session: 0x1498fa5e8e80001
21:44:25,781 [Thread-2] DEBUG ClientCnxn@close:Closing client for session: 0x1498fa5e8e80001
21:44:25,780 [Thread-1] DEBUG ClientCnxn@disconnect:Disconnecting client for session: 0x1498fa5e8e80000
21:44:25,780 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@readResponse:Got WatchedEvent state:SyncConnected type:NodeChildrenChanged path:/excavator/nondurable/DEFAULT/1.0.0-test/dd9beea4b272b1b02b60e12c1ba8c7f7 for sessionid 0x1498fa5e8e80001
21:44:25,782 [Thread-1] INFO  ZooKeeper@close:Session: 0x1498fa5e8e80000 closed
21:44:25,783 [main-EventThread] INFO  ClientCnxn$EventThread@run:EventThread shut down
21:44:25,784 [main-EventThread] ERROR PathChildrenCache@handleException:
java.lang.IllegalStateException
    at com.google.common.base.Preconditions.checkState(Preconditions.java:133)
    at com.netflix.curator.framework.imps.CuratorFrameworkImpl.getChildren(CuratorFrameworkImpl.java:294)
    at com.netflix.curator.framework.recipes.cache.PathChildrenCache.refresh(PathChildrenCache.java:361)
    at com.netflix.curator.framework.recipes.cache.PathChildrenCache.access$300(PathChildrenCache.java:64)
    at com.netflix.curator.framework.recipes.cache.PathChildrenCache$4.process(PathChildrenCache.java:352)
    at com.netflix.curator.framework.imps.NamespaceWatcher.process(NamespaceWatcher.java:38)
    at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:521)
    at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:497)
21:44:25,879 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@readResponse:Reading reply sessionid:0x1498fa5e8e80001, packet:: clientPath:null serverPath:null finished:false header:: 8,-11  replyHeader:: 8,111,0  request:: null response:: null
21:44:25,880 [Thread-2] DEBUG ClientCnxn@disconnect:Disconnecting client for session: 0x1498fa5e8e80001
21:44:25,880 [main-SendThread(server:2181)] DEBUG ClientCnxn$SendThread@run:An exception was thrown while closing send thread for session 0x1498fa5e8e80001 : Unable to read additional data from server sessionid 0x1498fa5e8e80001, likely server has closed socket
21:44:25,882 [main-EventThread] INFO  ClientCnxn$EventThread@run:EventThread shut down
21:44:25,881 [Thread-2] INFO  ZooKeeper@close:Session: 0x1498fa5e8e80001 closed
```

**Comment by oldmanpushcart** [comment]
你可以先忽略这个错误，这个错误是Provider、Consumer进程关闭时，关闭ZK，但curator的持久watch线程没有及时关闭所导致的错误，当此异常抛出时对应的服务实际已经下线，ZkClient已经断开，所以不会有功能上的问题。

我会考虑将这个异常尽可能优化掉，但对功能无伤大碍

**Comment by huangyong-git** [comment]
好的，希望能够顺利解决，期待！谢谢！
